### ISSUE TITLE
cannot create new issue when your repository doesn't have any issue template

### ISSUE THREAD

**Issue by yoshio15** [skanehira/gh.vim#102]
## 🐛 Summary
cannot create new issue when your repository doesn't have any issue template.
(could create new issue with repository which has issue templates.)

## 💔 Enviroment
- Vim Version: 8.2
- OS: macOS

## 👀 Steps
1. `vnew gh://:owner/:repo/issues/new` *the repo needs to have no issue template
2. enter title of new issue
3. press enter-key
4. close buffer and don't appear new issue buffer ( -> cannot input any issue body and never create new issue )

## 🆗 Expected
creating new issue will be successful even if the repo has no issue template.

## 🚑 Actual
cannot create new issue when the repo doesn't have any issue template.

## Cause
(I guess) at L295 of autoload/gh/issues.vim (inside of `s:open_template_list` function),
only if you don't have any issue template, execute `bw!`, which means invalidate `b:gh_issue_new`,
but try to access `b:gh_issue_new` variable after that (inside of `s:set_issue_template_buffer`).

I confirmed that I could create new issue if the repo has no issue template before.
[this change](https://github.com/skanehira/gh.vim/commit/7631328ec386a1e3227039fe3ea4e78ec96d79dc) seems to cause this issue.

**Comment by skanehira** [comment]
Thanks for detail issues :)
If your interesting, Wouldn't you fix this?

**Comment by yoshio15** [comment]
sure, I'm gonna try to fix this issue.
