### ISSUE TITLE
Allow autoselect owner and project of current directory(git repo)

### ISSUE THREAD

**Issue by korney4eg** [skanehira/gh.vim#124]
## 👔 Overview
Usually I work with single github repo at a time and open it in vim. There are also some plugins like vim-fugitive, vim-gitgutter and others that allows working with git itself. As an idea buffers name could be generated based on current information. For example I cloned repo `git@github.com:korney4eg/configs.git`, here I can see that owner is `korney4eg` and repo is `configs`. Using this information it would be much easier to list pull request by typing:
```vim
new gh://pr
```
or something similar.

## 👖 How to achieve
Try to read current remotes if possible and set appropriate variables.

## 🧦 Steps
1. run `git remote -v` and get owner and repo name
2. add short form of buffers without owner and repo in their line
3. if no remote or any other error, then show error in messages and thats all

**Comment by skanehira** [comment]
Thank you for issue, it's seems like good idea :)
I'll consider.

**Comment by skanehira** [comment]
I supported this in #125.
Please update plugin and try it :)

**Comment by korney4eg** [comment]
Hey @skanehira , thanks for your work.

Unfortunately for me your changes don't seem to work.

I updated plugin to version `e3c2806190143bc914948586e78cfcf73e5fe9b` and restarted nvim.

Here is my setup:
```
NVIM v0.5.0-dev+82100a6bd
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20201215-83436-1xsg4wm/build/config -I/tmp/neovim-20201215-83436-1xsg4wm/src -I/usr/local/include -I/tmp/neovim-20201215-83436-1xsg4wm/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20201215-83436-1xsg4wm/build/src/nvim/auto -I/tmp/neovim-20201215-83436-1xsg4wm/build/include
Скомпилирован  aliaksei.karneyeu@MBP-OK-78.local

Features: +acl +iconv +tui
```

I have cloned repo `git@github.com:learningdevops-makvaz-com/phase02_task02.git`

opening `README.md` in nvim.
If I type: `new gh://pulls` it doesn't show anything, only opens empty buffer
If I type: `new gh://learningdevops-makvaz-com/phase02_task02/pulls` it shows me pull requests list.

Thank you in advance.
