### ISSUE TITLE
issues: make it possible to edit multiple issues

### ISSUE THREAD

**Issue by skanehira** [skanehira/gh.vim#29]
use buffer variable instead of script variable

https://github.com/skanehira/gh.vim/blob/01df339a7f758c7af98f3a2aa1fd620efadaf402/autoload/gh/issues.vim#L343-L355

**Comment by ghost** [comment]
I'm gonna challenge fix it.

**Comment by hashue** [comment]
test

**Comment by hashue** [comment]
test 02

**Comment by skanehira** [comment]
done
