### ISSUE TITLE
No explanation that neovim is not available.

### ISSUE THREAD

**Issue by IN00** [skanehira/gh.vim#3]
gh.vimがtwitterのTLで流れてきて気になっていました。今回導入に至ったのですが自分の環境がneovimで動作せず疑問に思いながらたまたま、以下の記事を見てneovimで使えない事を知りました。
[ブラウザをやめてVimでGitHubを使う](https://zenn.dev/skanehira/articles/2020-09-19-vim-plugin-for-github)

お手すきで、こちらのリポジトリのREADMEにもneovimに対応していない旨の説明文を追加していただけるとなお良いのかなと思いました。

**Comment by skanehira** [comment]
そういえばREADMEに書いていませんでしたね
一応Neovimを対応したい気持ちはあるので、将来的には動かせるようにするつもりです
現時点でVimのみ動作する旨を記載しておきます
